# https://pnpm.io/settings
minimumReleaseAge: 10080
trustPolicy: no-downgrade
# trustPolicyExclude:
# - 'chokidar@4.0.3'
# - 'semver@6.3.1'
blockExoticSubdeps: true
allowBuilds:
  esbuild: false
  sharp: false
