const values = [
  {
    "creditProductType": "BNPL",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNPL",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC0",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 6,
    "maxTermMonths": 6,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 6,
    "maxTermMonths": 6,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 9,
    "maxTermMonths": 9,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 18,
    "maxTermMonths": 18,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC0",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC0",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC0",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC0",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC0",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 60,
    "maxTermMonths": 60,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNPL",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNPL",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNPL",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNPL",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 6,
    "maxTermMonths": 6,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 9,
    "maxTermMonths": 9,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 18,
    "maxTermMonths": 18,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 6,
    "maxTermMonths": 6,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 9,
    "maxTermMonths": 9,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 18,
    "maxTermMonths": 18,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC7",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 6,
    "maxTermMonths": 6,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC7",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 9,
    "maxTermMonths": 9,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC7",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC7",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 18,
    "maxTermMonths": 18,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC7",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC7",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IFC7",
    "creditProductCollectionType": "ExactMatch",
    "apr": 0.00,
    "monthlyRate": 0.0,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 6,
    "maxTermMonths": 6,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 60,
    "maxTermMonths": 60,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 60,
    "maxTermMonths": 60,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 6,
    "maxTermMonths": 6,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 60,
    "maxTermMonths": 60,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 6,
    "maxTermMonths": 6,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "IBC3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 9.90,
    "monthlyRate": 0.007897746915423776,
    "minDeferredMonths": 0,
    "maxDeferredMonths": 0,
    "minTermMonths": 60,
    "maxTermMonths": 60,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP1",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP2",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 12,
    "maxTermMonths": 12,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 6,
    "maxDeferredMonths": 6,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 24,
    "maxTermMonths": 24,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 36,
    "maxTermMonths": 36,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  },
  {
    "creditProductType": "BNP3",
    "creditProductCollectionType": "ExactMatch",
    "apr": 19.90,
    "monthlyRate": 0.015238935952665678,
    "minDeferredMonths": 12,
    "maxDeferredMonths": 12,
    "minTermMonths": 48,
    "maxTermMonths": 48,
    "minDeposit": 0.00,
    "minPurchaseAmount": 0.00
  }
];

const stringified = values.map((item) => {
  return JSON.stringify(item);
});
// console.log(valueArr);

const occurrences = stringified.reduce((acc, curr) => {
  return acc[curr] ? ++acc[curr] : acc[curr] = 1, acc
}, {});
console.log(occurrences);
